language: perl
perl:
    - "5.24"

notifications:
 email:
  recipients:
   - pk.roger@icloud.com
     
before_install:
    - yes | cpan -i Deep::Hash::Utils File::Basename File::Spec::Functions Getopt::Long XML::Simple YAML::Tiny
      
before_script:
 
script:
    - ./check-tools
