FROM pcm32/galaxy-stable-k8s
MAINTAINER PhenoMeNal-H2020 Project <phenomenal-h2020-users@googlegroups.com>

LABEL Description="Galaxy 17.05-phenomenal for running inside Kubernetes."
LABEL software="Galaxy"
LABEL version="2.0"
LABEL software.version="17.05-pheno-lr"

COPY config/galaxy.ini /home/galaxy/config/galaxy.ini
COPY config/job_conf.xml /home/galaxy/config/job_conf.xml
COPY config/tool_conf.xml /home/galaxy/config/tool_conf.xml
COPY config/sanitize_whitelist.txt /home/galaxy/config/sanitize_whitelist.txt
COPY tools/phenomenal /home/galaxy/tools/phenomenal

COPY html/partners.png /home/galaxy/web/partners.png
COPY html/PhenoMeNal_logo.png /home/galaxy/web/PhenoMeNal_logo.png
COPY html/welcome.html /home/galaxy/web/welcome.html
COPY ansible /home/galaxy/ansible
COPY workflows /home/galaxy/workflows
COPY container-simple-checks.sh container-simple-checks.sh
COPY test_cmds.txt test_cmds.txt
