FROM pcm32/galaxy-init-pheno

MAINTAINER PhenoMeNal-H2020 Project <phenomenal-h2020-users@googlegroups.com>

LABEL Description="Galaxy 17.05-phenomenal for running inside Kubernetes."
LABEL software="Galaxy Init"
LABEL software.version="17.05-pheno-lr"
LABEL version="1.3"

#COPY config/galaxy.ini config/galaxy.ini
COPY config/job_conf.xml config/job_conf.xml
COPY config/tool_conf.xml config/tool_conf.xml
COPY config/sanitize_whitelist.txt config/sanitize_whitelist.txt
COPY tools/phenomenal tools/phenomenal

# Reqs/limits
COPY config/job_resource_params_conf.xml config/job_resource_params_conf.xml
COPY config/phenomenal_tools2container.yaml config/phenomenal_tools2container.yaml
COPY rules/k8s_destinations.py /galaxy-central/lib/galaxy/jobs/rules/k8s_destination.py

# Galaxy tours which guide users through the subsequent steps in an analysis
COPY config/plugins/tours/*.yaml config/plugins/tours/

COPY html/partners.png welcome/welcome_partners.png
COPY html/PhenoMeNal_logo.png welcome/welcome_PhenoMeNal_logo.png
COPY html/welcome.html welcome/welcome.html

COPY ansible ansible
COPY workflows workflows_to_load
COPY container-simple-checks.sh container-simple-checks.sh
COPY test_cmds.txt test_cmds.txt
COPY post-start-actions.sh post-start-actions.sh
RUN chmod u+x post-start-actions.sh

# Missing XCMS datatypes for w4m
COPY external-datatypes/rdata_xcms_datatype.py /galaxy-central/lib/galaxy/datatypes/
COPY external-datatypes/rdata_camera_datatype.py /galaxy-central/lib/galaxy/datatypes/
COPY external-datatypes/no_unzip_datatypes.py /galaxy-central/lib/galaxy/datatypes/
COPY external-datatypes/nmrml_datatype.py /galaxy-central/lib/galaxy/datatypes/
COPY config/datatypes_conf.xml config/datatypes_conf.xml
