FROM container-registry.phenomenal-h2020.eu/phnmnl/galaxy-init-pheno-flavoured:dev_v18.01-pheno-isa_cv1.7.301

MAINTAINER PhenoMeNal-H2020 Project <phenomenal-h2020-users@googlegroups.com>

LABEL Description="Galaxy 18.01-pheno-dev for running inside Kubernetes."
LABEL software="Galaxy Init"
LABEL software.version="18.01-pheno-dev"
LABEL version="1.7"

# Patch for up to 18.05-dev only, not tested on 19.01 and should not be used >= 19.05
# Avoids failure due to missing errored job in k8s (line 499)
COPY patches/kubernetes.py /galaxy-export/galaxy-central/lib/galaxy/jobs/runners/kubernetes.py

#COPY config/galaxy.ini config/galaxy.ini
COPY config/job_conf.xml config/job_conf.xml
RUN sed -i 's/HANDLERS -->//' config/job_conf.xml && sed -i 's/<!-- HANDLERS//g' config/job_conf.xml
COPY config/tool_conf.xml config/tool_conf.xml
COPY config/sanitize_whitelist.txt config/sanitize_whitelist.txt
COPY tools/phenomenal tools/phenomenal

# Reqs/limits
COPY config/job_resource_params_conf.xml config/job_resource_params_conf.xml
COPY config/phenomenal_tools2container.yaml config/phenomenal_tools2container.yaml
COPY rules/k8s_destinations.py /galaxy-central/lib/galaxy/jobs/rules/k8s_destination.py

# Galaxy tours which guide users through the subsequent steps in an analysis
COPY config/plugins/tours/*.yaml config/plugins/tours/

# Galaxy visualization plugins to add extra visualization capability to datasets
COPY config/plugins/visualizations/isatab-viewer config/plugins/visualizations/isatab-viewer/
COPY config/plugins/visualizations/isatab-viewer/static/ /galaxy-central/static/plugins/visualizations/isatab-viewer/static/

COPY html/partners.png welcome/welcome_partners.png
COPY html/PhenoMeNal_logo.png welcome/welcome_PhenoMeNal_logo.png
COPY html/welcome.html welcome/welcome.html

COPY ansible ansible
COPY workflows workflows_to_load
COPY container-simple-checks.sh container-simple-checks.sh
COPY test_cmds.txt test_cmds.txt
COPY post-start-actions.sh post-start-actions.sh
RUN chmod u+x post-start-actions.sh

# Missing XCMS datatypes for w4m
COPY external-datatypes/rdata_xcms_datatype.py /galaxy-central/lib/galaxy/datatypes/
COPY external-datatypes/rdata_camera_datatype.py /galaxy-central/lib/galaxy/datatypes/
COPY external-datatypes/nmrml_datatype.py /galaxy-central/lib/galaxy/datatypes/
COPY config/datatypes_conf.xml config/datatypes_conf.xml
