#!/bin/bash
# vi: fdm=marker

# Constants {{{1
################################################################

TOOLS="univariate multivariate biosigner lcmsmatching"

# MAIN {{{1
################################################################

# Loop on all tools
for tool in $TOOLS ; do

	# Pull container
	docker pull container-registry.phenomenal-h2020.eu/phnmnl/$tool:latest

	# Extract tool source code from container
	docker rm $tool
	docker run --name $tool --entrypoint=true container-registry.phenomenal-h2020.eu/phnmnl/$tool
	rm -rf tool_src
	docker cp $tool:/files/$tool tool_src

	# Copy files
	[ -e tool_src/${tool}_config.xml ] && cp tool_src/${tool}_config.xml .
	for python_script in $(ls tool_src/*.py 2>/dev/null) ; do cp $python_script . ; done
	[ -d tool_src/static ] && cp -r tool_src/static .

	# Modify tool command line in XML config file 
	sed -e 's/Rscript//' -e 's!\$__tool_directory__/!!' -i '' ${tool}_config.xml
done
